### ISSUE TITLE
Adding track.artist

### ISSUE THREAD

**Issue by yaniswav** [Run1e/spoofy#13]
`from asyncspotify import Client, ClientCredentialsFlow

auth = ClientCredentialsFlow(
   client_id='your client id',
   client_secret='your client secret',
)

async with Client(auth) as sp:
   playlist = await sp.get_playlist('1MG01HhbCvVhH9NmXhd9GC')
   async for track in playlist:
      print(track.name)`

it could be cool that we can print track.artist

**Comment by Run1e** [comment]
Hi,

`Track` objects have an attribute `artists` (as tracks can have several artists). If you want the first artist you can do `track.artists[0]`

See `Track` interface here: https://asyncspotify.readthedocs.io/en/latest/api.html#track

**Comment by yaniswav** [comment]
Thank you very much !
