### ISSUE TITLE
Implement audio-analysis endpoint (excellent starter issue)

### ISSUE THREAD

**Issue by Run1e** [Run1e/spoofy#9]
https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/

**Comment by Ara225** [comment]
Hi,
Had a quick crack at this today and have done a basic implementation. Think it could do with a bit more love though, so will hold off on a pull request for now.

**Comment by Run1e** [comment]
Nice! Will review once you get the PR submitted.
